name: CCIS1301  # CHANGE ME
baseurl: /morea-core-custom # CHANGE ME
github_org_url: https://github.com/htc-ccis1301-spring2017 # CHANGE ME
github_org_name: "HTC CCIS1301 Spring 2017" # CHANGE ME

# The following properties should not need to change semester to semester.
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

gems:
  - jekyll-gist
  - jemoji

morea_course: CCIS 1301
morea_domain: http://htc-ccis1301.github.io/
morea_google_analytics_tracking_id: "UA-63189236-5"
