name: "CCIS1301"  # CHANGE ME
baseurl: /semester # CHANGE ME
github_org_url: https://github.com/htc-ccis1301-semester # CHANGE ME
github_org_name: "HTC CCIS1301 Semester" # CHANGE ME

# The following properties should not need to change semester to semester.
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

gems:
  - jekyll-gist
  - jemoji

# CHANGE for each course template, but no need to change each semester
morea_course: CCIS 1301
morea_domain: http://htc-ccis1301.github.io/
morea_google_analytics_tracking_id: "UA-63189236-5"
googleCalendarId: '8g28fk9ir2radvqoeq1n68sk1s@group.calendar.google.com'
