name: CCIS1301  # CHANGE ME
baseurl: /morea-core-custom # CHANGE ME

markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
mathjax: true
exclude: [morea]
morea_theme: spacelab
morea_navbar_items:
  #- Prerequisites
  - Modules
  - Outcomes
  - Readings
  - Experiences
  - Assessments
  - Schedule

gems:
  - jekyll-gist
  - jemoji

# The following properties are optional.
# See the User Guide (http://morea-framework.github.io/userguide.html) for more info.

morea_course: CCIS 1301
morea_domain: http://htc-ccis1301.github.io/
morea_google_analytics_tracking_id: "UA-63189236-5"

#morea_head_breadcrumb_link: "http://cnn.com"
#morea_head_breadcrumb_label: "CNN Site"
